name: lovers_dictionary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  image_cropper: ^8.0.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # 自动化生成 App 图标的插件
  flutter_launcher_icons: ^0.13.1

# 桌面图标生成配置
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # 注册本地静态资源目录
  assets:
    - assets/images/app_logo.png